import type { Metadata } from 'next';
import { GoogleTagManager } from '@next/third-parties/google';
import { Josefin_Sans } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import { i18n, Locale } from '../../../i18n.config';
import { getDictionary } from '@/utils/dictionaries';

import Aos from '@/components/common/Aos';

import DictionaryProvider from '@/providers/DictionaryProvider';
import ThemeProvider from '@/providers/ThemeProvider';
import QueryClientProvider from '@/providers/QueryClientProvider';

import '@radix-ui/themes/styles.css';
import 'aos/dist/aos.css'; // You can also use <link> for styles
import './theme-config.css';
import './globals.css';

type Props = Readonly<{ children: React.ReactNode; params: { lang: Locale } }>;

const josefinSans = Josefin_Sans({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Exactrem',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

async function RootLayout({ children, params }: Props) {
	const dictionary = await getDictionary(params.lang);

	return (
		<html lang={params.lang}>
			<GoogleTagManager gtmId={process.env.NEXT_GTM as string} />

			<body className={josefinSans.className}>
				<Toaster position="bottom-center" />
				<Aos />

				<QueryClientProvider>
					<DictionaryProvider dictionary={dictionary}>
						<ThemeProvider>{children}</ThemeProvider>
					</DictionaryProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}

export default RootLayout;
