import type { Metadata } from 'next';

import { GoogleTagManager } from '@next/third-parties/google';
import { Toaster } from 'react-hot-toast';
import { josefinSans } from '@/utils/fonts';

import Aos from '@/components/common/Aos';
import ChatBot from '@/components/ui/ChatBot';

import AuthProvider from '@/providers/AuthProvider';
import QueryClientProvider from '@/providers/QueryClientProvider';
import ThemeProvider from '@/providers/ThemeProvider';

import '@radix-ui/themes/styles.css';
import 'aos/dist/aos.css';
import 'animate.css';

import './theme-config.css';
import './globals.css';

export const metadata: Metadata = {
	title: 'Exactrem',
	description: 'Generated by create next app',
};

async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html>
			<GoogleTagManager gtmId={process.env.NEXT_GTM as string} />

			<body className={josefinSans.className}>
				<Toaster position="bottom-center" />
				<Aos />

				<QueryClientProvider>
					<AuthProvider>
                        <ThemeProvider>
                            {children}
                            
                            <ChatBot />
                        </ThemeProvider>
					</AuthProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}

export default RootLayout;
